.DEFAULT_GOAL=all
DEPENDS=$(patsubst %c,%d,$(wildcard *.c))
DEPENDS2=$(patsubst %c,%d,$(wildcard ../common/*.c))

ifneq ($(MAKECMDGOALS),)
MAKECMDGOALS=all
endif

ifneq ($(MAKECMDGOALS),clean)
include $(DEPENDS)
include $(DEPENDS2)
endif
